-- ============================================================
-- Online Equipment Borrowing and Return Monitoring System
-- Supabase PostgreSQL Schema + RLS + Seed Data
-- Run this in Supabase Dashboard > SQL Editor > New query
-- ============================================================

-- 1. EQUIPMENT TABLE
CREATE TABLE IF NOT EXISTS public.equipment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_name TEXT NOT NULL,
  category TEXT NOT NULL,
  asset_code TEXT UNIQUE NOT NULL,
  condition TEXT DEFAULT 'Good',
  availability TEXT DEFAULT 'Available',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. BORROW TRANSACTIONS TABLE
CREATE TABLE IF NOT EXISTS public.borrow_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_id BIGINT REFERENCES public.equipment(id),
  borrower_name TEXT NOT NULL,
  borrower_type TEXT NOT NULL,
  department TEXT NOT NULL,
  date_borrowed DATE DEFAULT CURRENT_DATE,
  due_date DATE NOT NULL,
  date_returned DATE,
  status TEXT DEFAULT 'Borrowed',
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ROW LEVEL SECURITY
ALTER TABLE public.equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.borrow_transactions ENABLE ROW LEVEL SECURITY;

-- Equipment policies: only signed-in users can read and manage records
DROP POLICY IF EXISTS "equipment_all_auth" ON public.equipment;
CREATE POLICY "equipment_all_auth"
  ON public.equipment
  FOR ALL
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

-- Borrow transactions policies
DROP POLICY IF EXISTS "borrow_all_auth" ON public.borrow_transactions;
CREATE POLICY "borrow_all_auth"
  ON public.borrow_transactions
  FOR ALL
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

-- 4. SEED DATA (optional - sample equipment records)
-- You may uncomment the lines below to load sample data.
--
-- INSERT INTO public.equipment (equipment_name, category, asset_code, condition, availability)
-- VALUES
--   ('Epson Projector',   'Projector',        'PROJ-001', 'Good',     'Available'),
--   ('Acer Laptop',       'Laptop',           'LAP-002',  'Good',     'Available'),
--   ('Canon DSLR Camera', 'Camera',           'CAM-003',  'Good',     'Available'),
--   ('Wireless Headset',  'Microphone',       'MIC-004',  'Fair',     'Available'),
--   ('TP-Link Router',    'Router',           'RTR-005',  'Good',     'Available'),
--   ('Extension Cord',    'Extension Cord',   'EXT-006',  'Good',     'Available'),
--   ('HDMI Cable',        'HDMI Cable',       'HDM-007',  'Good',     'Available'),
--   ('Computer Toolkit',  'Computer Toolkit', 'TOL-008',  'Fair',     'Available'),
--   ('Portable Speaker',  'Portable Speaker', 'SPK-009',  'Good',     'Available'),
--   ('Interactive Board', 'Other ICT Equipment', 'BOD-010', 'For Repair', 'Available');